/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Surface tokens
        "surface": "#ffffff",
        "surface-dim": "#d9dadb",
        "surface-bright": "#ffffff",
        "surface-variant": "#E8F0F6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#F4F8FC",
        "surface-container": "#E8F0F6",
        "surface-container-high": "#D6E6F3",
        "surface-container-highest": "#A6C5D7",
        "surface-tint": "#0F52BA",
        "on-surface": "#000926",
        "on-surface-variant": "#4B5563",
        "inverse-surface": "#000926",
        "inverse-on-surface": "#F7FAFC",
        "background": "#F7FAFC",
        "on-background": "#000926",
        // Primary
        "primary": "#0F52BA",
        "on-primary": "#FFFFFF",
        "primary-container": "#3A7BFF",
        "on-primary-container": "#FFFFFF",
        "primary-fixed": "#D6E6F3",
        "primary-fixed-dim": "#A6C5D7",
        "on-primary-fixed": "#000926",
        "on-primary-fixed-variant": "#0F52BA",
        "inverse-primary": "#A6C5D7",
        // Secondary
        "secondary": "#5B6775",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#E8F0F6",
        "on-secondary-container": "#5B6775",
        "secondary-fixed": "#E8F0F6",
        "secondary-fixed-dim": "#A6C5D7",
        "on-secondary-fixed": "#000926",
        "on-secondary-fixed-variant": "#5B6775",
        // Tertiary
        "tertiary": "#0F52BA",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#E8F0F6",
        "on-tertiary-container": "#0F52BA",
        "tertiary-fixed": "#D6E6F3",
        "tertiary-fixed-dim": "#A6C5D7",
        "on-tertiary-fixed": "#000926",
        "on-tertiary-fixed-variant": "#0F52BA",
        // Error
        "error": "#BA1A1A",
        "on-error": "#FFFFFF",
        "error-container": "#FFDAD6",
        "on-error-container": "#93000a",
        // Custom premium status colors
        "danger": "#D92D20",
        "danger-light": "#FEE4E2",
        "success": "#079455",
        "success-light": "#D1FADF",
        "warning": "#DC6803",
        "warning-light": "#FEF0C7",
        // Outline
        "outline": "#A6C5D7",
        "outline-variant": "#D6E6F3",
      },
      spacing: {
        "topbar_height": "56px",
        "sidebar_width": "240px",
        "container_gap": "24px",
        "btn_height_cta": "40px",
        "btn_height_default": "36px",
        "input_height": "36px",
        "card_padding": "16px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body": ["Inter", "sans-serif"],
        "card-title": ["Inter", "sans-serif"],
        "overline": ["Inter", "sans-serif"],
        "section-header": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "tiny": ["Inter", "sans-serif"],
        "h1-font": ["Inter", "sans-serif"],
        "secondary-font": ["Inter", "sans-serif"],
      },
      fontSize: {
        "overline": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
        "body": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "section-header": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "secondary": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "tiny": ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "h1": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "card-title": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "data-mono": ["13px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
